### ISSUE TITLE
Console does not work with Idea 13 133.193

### ISSUE THREAD

**Issue by mstarzyk** [JetBrains/la-clojure#74]
Looks like la-clojure 0.7.60 is not compatible with the Idea 13 API. 
Clojure REPL opens, but does not output anything. There is a NoSuchMethodError in Idea logs:

```
2013-12-06 10:17:17,418 [  36704]  ERROR - llij.ide.plugins.PluginManager - com.intellij.execution.console.LanguageConsoleImpl.printToConsole(Lcom/intellij/execution/console/LanguageConsoleImpl;Lcom/intellij/execution/ui/ConsoleViewContentType;Ljava/util/List;)V 
java.lang.NoSuchMethodError: com.intellij.execution.console.LanguageConsoleImpl.printToConsole(Lcom/intellij/execution/console/LanguageConsoleImpl;Lcom/intellij/execution/ui/ConsoleViewContentType;Ljava/util/List;)V
    at org.jetbrains.plugins.clojure.repl.ClojureConsoleHighlightingUtil.processOutput(ClojureConsoleHighlightingUtil.java:38)
    at org.jetbrains.plugins.clojure.repl.ClojureConsoleProcessHandler.textAvailable(ClojureConsoleProcessHandler.java:26)
    at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:53)
    at com.intellij.execution.process.AnsiEscapeDecoder.coloredTextAvailable(AnsiEscapeDecoder.java:96)
    at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
    at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:48)
    at com.intellij.execution.process.BaseOSProcessHandler.startNotify(BaseOSProcessHandler.java:79)
    at org.jetbrains.plugins.clojure.repl.ClojureConsoleRunner.initAndRun(ClojureConsoleRunner.java:181)
    at org.jetbrains.plugins.clojure.repl.ClojureConsoleRunner.run(ClojureConsoleRunner.java:113)
    at org.jetbrains.plugins.clojure.actions.RunClojureConsoleAction.actionPerformed(RunClojureConsoleAction.java:54)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:493)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2013-12-06 10:17:17,421 [  36707]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 13.0  Build #IC-133.193 
2013-12-06 10:17:17,421 [  36707]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_45 
2013-12-06 10:17:17,421 [  36707]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2013-12-06 10:17:17,421 [  36707]  ERROR - llij.ide.plugins.PluginManager - Vendor: Sun Microsystems Inc. 
2013-12-06 10:17:17,422 [  36708]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2013-12-06 10:17:17,422 [  36708]  ERROR - llij.ide.plugins.PluginManager - Last Action: org.jetbrains.plugins.clojure.actions.RunClojureConsoleAction 
```
